### ISSUE TITLE
Convert Zero-to-Binder tutorial into R and Julia languages

### ISSUE THREAD

**Issue by sgibson91** [sgibson91/ssi-fellowship#3]
### Summary

This issue will track the conversion of the [Zero-to-Binder](https://bit.ly/zero-to-binder-tutorial) into Julia and R so that there is a Binder introductory resource for all three languages.

### What needs to be done?

- [x] Find Julia and R experts to collaborate with
- [x] Decide what aspects of Julia and R integrations we want to demonstrate in the tutorial
  - [x] **R:** `install.R` versus `NAMESPACE` and `DESCRIPTION`
  - [x] **R:** Using RStudio versus Notebooks
- [x] Convert the tutorials and contribute them to _The Turing Way_

### Who can help?

- Anna Krystalli for R version
- Potentially someone in Turing REG knows Julia? If not, ask in the SSI and/or Binder communities

**Comment by willingc** [comment]
@xorJane would be a fabulous resource for information about Julia.

@fperez may know others in the Jupyter world who work with Julia. @davidantoff has been very helpful with Julia and nteract examples/feedback.

**Comment by davidanthoff** [comment]
I’d be happy to be a contact on the Julia side. I won’t have time to do any actual work :) But happy to answer questions etc.

**Comment by sgibson91** [comment]
Thank you all! @davidanthoff I'll definitely let you know if I run into anything strange :)

**Comment by sgibson91** [comment]
@ots22 is interested on working on the Julia version. We'll have another discussion in early March once our calendars have eased off.

@annakrystalli interested in working on the R version. To be done in April.

**Comment by sgibson91** [comment]
#### Tracking Julia translation

Issue: https://github.com/alan-turing-institute/the-turing-way/issues/952
PR: TBA

**Comment by sgibson91** [comment]
R version of Zero-to-Binder! https://github.com/alan-turing-institute/the-turing-way/pull/1139#pullrequestreview-419020496

**Comment by sgibson91** [comment]
Hey @davidanthoff 👋 I wonder if you could help me re-word the below paragraph to be more relevant to Julia? Thanks!

> ### More on pinning dependencies
>
> In the above example, we used two equals signs (`==`) to pin the version of `numpy`.
> This tells Binder to install that _specific_ version.
>
> Another way to pin a version number is to use the greater than or equal to sign (`>=`) to allow any version above a particular one to be installed.
> This is useful when you have a lot of dependencies that may have dependencies on each other and allows Binder to find a configuration of your dependencies that do not conflict with one another whilst avoiding any earlier versions which may break or change your code.
>
> Finally, you could not provide a version number at all (just the name of the library/package) and Binder will install the latest version of that package.
>
> **N.B.:** These operations to pin dependencies are most likely specific to Python.
> Each language has it's own quirks and a link to the different types of configuration files (which is what `requirements.txt` is) is given at the bottom of this document.

**Comment by davidanthoff** [comment]
So the general idea for Julia is that you put a `Project.toml` and `Manifest.toml` in the root of your github repo. You typically don't create them by hand, but use the built-in package manager to create them (docs for that are [here](https://julialang.github.io/Pkg.jl/v1/environments/)). The combination of `Project.toml` and `Manifest.toml` pins every package to a specific version, so when binder starts up, you'll get an exact replication of the package versions that were originally used, including all dependencies of dependencies etc.

**Comment by sgibson91** [comment]
And Julia is now done! http://bit.ly/zero-to-binder-julia 🎉 Thanks everybody!
